<?php

namespace AppBundle\Repository;

/**
 * TotalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotalRepository extends \Doctrine\ORM\EntityRepository
{
}
